server:
  port: 8081
  servlet:
    context-path: /Evidencia-31
    
  error:
    include-details: always
       
       #Conexion MYSQL
spring:
  datasource:
    url:jdbc: mysql://localhost:3306/aula
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
#configuracion JPA



# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka

    